Add matrix/parallel examples

diff --git a/.semaphore/semaphore.yml b/.semaphore/semaphore.yml
--- a/.semaphore/semaphore.yml
+++ b/.semaphore/semaphore.yml
@@ -10,25 +10,43 @@ after_pipeline:
       - name: Reports
         commands:
           - test-results gen-pipeline-report
-      - name: Long job
+      - name: Job 1
         commands:
-          - echo I RUN FOR A LONG TIME
-          - sleep 10
-      - name: Failed job
+          - exit 0
+      - name: Job 2
         commands:
-          - echo I FAIL!
-          - sleep 1
-          - exit 1
+          - exit 0
+      - name: Job 3
+        commands:
+          - exit 0
+      - name: Job 4
+        commands:
+          - exit 0
       - name: Pipeline metrics
         commands:
           - >-
-            echo "SEMAPHORE_PIPELINE_DURATION=${SEMAPHORE_PIPELINE_DURATION}" &&
-            echo "SEMAPHORE_PIPELINE_DURATION_INIT=${SEMAPHORE_PIPELINE_DURATION_INIT}" &&
-            echo "SEMAPHORE_PIPELINE_DURATION_QUEUEING=${SEMAPHORE_PIPELINE_DURATION_QUEUEING}" &&
-            echo "SEMAPHORE_PIPELINE_DURATION_RUNNING=${SEMAPHORE_PIPELINE_DURATION_RUNNING}" &&
+            echo "SEMAPHORE_PIPELINE_TOTAL_DURATION=${SEMAPHORE_PIPELINE_TOTAL_DURATION}" &&
+            echo "SEMAPHORE_PIPELINE_INIT_DURATION=${SEMAPHORE_PIPELINE_INIT_DURATION}" &&
+            echo "SEMAPHORE_PIPELINE_QUEUEING_DURATION=${SEMAPHORE_PIPELINE_QUEUEING_DURATION}" &&
+            echo "SEMAPHORE_PIPELINE_RUNNING_DURATION=${SEMAPHORE_PIPELINE_RUNNING_DURATION}" &&
             echo "SEMAPHORE_PIPELINE_CREATED_AT=${SEMAPHORE_PIPELINE_CREATED_AT}($(date -d @${SEMAPHORE_PIPELINE_CREATED_AT}))" &&
             echo "SEMAPHORE_PIPELINE_STARTED_AT=${SEMAPHORE_PIPELINE_STARTED_AT}($(date -d @${SEMAPHORE_PIPELINE_STARTED_AT}))" &&
-            echo "SEMAPHORE_PIPELINE_DONE_AT=${SEMAPHORE_PIPELINE_DONE_AT}($(date -d @${SEMAPHORE_PIPELINE_DONE_AT}))"
+            echo "SEMAPHORE_PIPELINE_DONE_AT=${SEMAPHORE_PIPELINE_DONE_AT}($(date -d @${SEMAPHORE_PIPELINE_DONE_AT}))" &&
+            echo "SEMAPHORE_PIPELINE_STATE=${SEMAPHORE_PIPELINE_STATE}" &&
+            echo "SEMAPHORE_PIPELINE_RESULT=${SEMAPHORE_PIPELINE_RESULT}" &&
+            echo "SEMAPHORE_PIPELINE_RESULT_REASON=${SEMAPHORE_PIPELINE_RESULT}"
+      - name: Parallel job
+        parallelism: 2
+        commands:
+          - echo Job $SEMAPHORE_JOB_INDEX out of $SEMAPHORE_JOB_COUNT
+      - name: Matrix job
+        matrix:
+          - env_var: FOO
+            values: [ "A", "B" ]
+          - env_var: BAR
+            values: [ "1", "2" ]
+        commands:
+          - echo FOO=$FOO BAR=$BAR
 blocks:
   - name: Run tests
     task:
@@ -36,18 +54,16 @@ blocks:
         - name: Test
           parallelism: 2
           commands:
-            - sleep 10
             - checkout
-            - echo Publishing ${SEMAPHORE_JOB_INDEX}/${SEMAPHORE_JOB_COUNT} test
             - test-results publish test/junit-${SEMAPHORE_JOB_INDEX}.xml
-        - name: Test failed
-          parallelism: 1
-          commands:
-            - sleep 10
-            - checkout
-            - echo Publishing ${SEMAPHORE_JOB_INDEX}/${SEMAPHORE_JOB_COUNT} test
-            - test-results publish test/junit-failed-${SEMAPHORE_JOB_INDEX}.xml
-            - exit 1
+        # - name: Test failed
+        #   parallelism: 1
+        #   commands:
+        #     - sleep 10
+        #     - checkout
+        #     - echo Publishing ${SEMAPHORE_JOB_INDEX}/${SEMAPHORE_JOB_COUNT} test
+        #     - test-results publish test/junit-failed-${SEMAPHORE_JOB_INDEX}.xml
+        #     - exit 1
 promotions:
   - name: Promo
     pipeline_file: promo.yml
